language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
before_script:
  - sudo apt-get install pychecker pylint pep8
install:
script: "python setup.py nosetests"
notifications:
  email:
    - normes@normes.org
